name: Code Review

on:
  pull_request:
    branches:
      - develop

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Lint
        run: |
          make lint
      - name: Test
        run: make test
