name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker base image
        id: build-base-image
        run: |
          make build-base

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: koorinc/genesis:${{  github.ref_name }}

